### ISSUE TITLE
Feature request from #2: implement remote control

### ISSUE THREAD

**Issue by fabiofenoglio** [fabiofenoglio/lelo-f1-hub#7]
> I think there should be a way for someone to remotely control the F1s from the hub. Now that you implemented an account based system, starting a shared session could be easier and not have to expose your IP.

@slycooper724
extracted from https://github.com/fabiofenoglio/lelo-f1-hub/issues/2

**Comment by slycooper724** [comment]
Any progress on the project?

**Comment by fabiofenoglio** [comment]
Hello @slycooper724 , development of the remote control feature is ongoing but proceeding slower than expected due to personal issues (CODIV-19 hit pretty hard)
I'll keep you up to date

**Comment by slycooper724** [comment]
@fabiofenoglio
Sorry to hear that, and I totally understand. Take your time man, It's worth the wait. 😁

**Comment by fabiofenoglio** [comment]
@slycooper724 an update has been released, including a beta version of remote control available for testing.
Any feedback on the feature would be greatly appreciated

**Comment by slycooper724** [comment]
I just tested the remote feature with an emulated device, and used a VPN and etc to simulate a long distance connection and everything checked out properly. My only suggestion would to implement a backend system that can handle translating a link to a remote access code for more accessible sharing of remote sessions. I really appreciate the work your putting into this, and I love the choice of backend/frontend since it's clean and works really damn well.

**Comment by fabiofenoglio** [comment]
@slycooper724 thank you for testing and your kind feedback!
A shareable link for remote control is a great idea, I'll extract a new issue and schedule it for the next release. Thank you.
